global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['YOUR-IP:8403']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['YOUR-IP:8405']
        labels:
          instance: 'node_exporter'
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['YOUR-IP:8408']
        labels:
          instance: 'redis_exporter'
  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['YOUR-IP:8409']
        labels:
          instance: 'mysql_exporter'
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['YOUR-IP:8407']
        labels:
          instance: 'cadvisor'

  - job_name: 'rd-server-system-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['YOUR-IP:8201']
        labels:
          instance: 'rd-server-system'
  - job_name: 'rd-server-auth-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['YOUR-IP:8101']
        labels:
          instance: 'rd-auth'
  - job_name: 'rd-server-test-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['YOUR-IP:8202']
        labels:
          instance: 'rd-server-test'
  - job_name: 'rd-server-job-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['YOUR-IP:8204']
        labels:
          instance: 'rd-server-job'
  - job_name: 'rd-tx-manager-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['YOUR-IP:8501']
        labels:
          instance: 'rd-tx-manager'
rule_files:
  - 'memory_over.yml'
  - 'server_down.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["YOUR-IP:8406"]