version: '3'

services:
  rd-admin:
    image: rd-admin:latest
    container_name: rd-admin
    volumes:
      - "/data/logs:/data/logs"
    command:
      - "--nacos.url=127.0.0.1"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8401:8401
    restart: on-failure
  rd-gateway:
    image: rd-gateway:latest
    container_name: rd-gateway
    volumes:
      - "/data/logs:/data/logs"
    command:
      - "--rd-admin=127.0.0.1"
      - "--mongo.url=127.0.0.1"
      - "--nacos.url=127.0.0.1"
      - "--redis.url=127.0.0.1"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8301:8301
    restart: on-failure
  rd-auth:
    image: rd-auth:latest
    container_name: rd-auth
    volumes:
      - "/data/logs:/data/logs"
    command:
      - "--rd-admin=127.0.0.1"
      - "--nacos.url=127.0.0.1"
      - "--mysql.url=127.0.0.1"
      - "--redis.url=127.0.0.1"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8101:8101
    restart: on-failure
  rd-server-system:
    image: rd-server-system:latest
    container_name: rd-server-system
    volumes:
      - "/data/logs:/data/logs"
    command:
      - "--rd-admin=127.0.0.1"
      - "--rd-gateway=127.0.0.1"
      - "--nacos.url=127.0.0.1"
      - "--mysql.url=127.0.0.1"
      - "--rd-tx-manager=127.0.0.1"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8201:8201
    depends_on:
      - rd-tx-manager
    restart: on-failure
  rd-server-test:
    image: rd-server-test:latest
    container_name: rd-server-test
    volumes:
      - "/data/logs:/data/logs"
    command:
      - "--nacos.url=127.0.0.1"
      - "--rd-admin=127.0.0.1"
      - "--mysql.url=127.0.0.1"
      - "--rd-tx-manager=127.0.0.1"
      - "--rd-gateway=127.0.0.1"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8202:8202
    depends_on:
      - rd-tx-manager
    restart: on-failure
  rd-server-generator:
    image: rd-server-generator:latest
    container_name: rd-server-generator
    volumes:
      - "/data/logs:/data/logs"
    command:
      - "--nacos.url=127.0.0.1"
      - "--rd-admin=127.0.0.1"
      - "--mysql.url=127.0.0.1"
      - "--rd-gateway=127.0.0.1"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8203:8203
    restart: on-failure
  rd-server-job:
    image: rd-server-job:latest
    container_name: rd-server-job
    volumes:
      - "/data/logs:/data/logs"
    command:
      - "--nacos.url=127.0.0.1"
      - "--rd-admin=127.0.0.1"
      - "--mysql.url=127.0.0.1"
      - "--rd-gateway=127.0.0.1"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8204:8204
    restart: on-failure
  rd-tx-manager:
    image: rd-tx-manager:latest
    container_name: rd-tx-manager
    volumes:
      - "/data/logs:/data/logs"
    command:
      - "--nacos.url=127.0.0.1"
      - "--rd-admin=127.0.0.1"
      - "--mysql.url=127.0.0.1"
      - "--redis.url=127.0.0.1"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8501:8501
      - 8888:8888
    restart: on-failure
  rd-cloud-web:
    image: rd-cloud-web
    container_name: rd-cloud-web
    volumes:
      - "/data/logs:/data/logs"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 9527:80
    restart: on-failure
