#FROM openjdk:8u212-jre
FROM openjdk:11.0.8-jre

MAINTAINER lh@erongdu.com

COPY ./target/rd-server-activiti-2.1-RELEASE.jar /rd/rd-server-activiti-2.1-RELEASE.jar

CMD ["java","-jar","/rd/rd-server-activiti-2.1-RELEASE.jar"]